# Site settings
title:          Joshua "Baus" Paget
description:    ""
baseurl:        "/website"
url:            "https://joshbaus.com"

# Author
author:
  name:         Joshua "Baus" Paget
  url:          https://joshbaus.com
  email:        contact@joshbaus.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
